# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyStroke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_times', models.TextField()),
                ('dwell_times', models.TextField()),
                ('type', models.IntegerField(choices=[(1, 'Login'), (2, 'Password')])),
                ('is_temporary', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='keystroke',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='keystroke_auth_server.User'),
        ),
    ]
